version: '3'

services:

  servlet:
    image: servlet:latest
    restart: always
    container_name: servlet_container
    environment:
      APP_NAME: 'servlet'
      HSQLDB_HOST: hsqldb
      HSQLDB_USER: SA
      HSQLDB_PASSWORD:
    build:
      context: com.qulix.yurkevichvv.trainingtask.servlets
    ports:
      - "80:8080"
    depends_on:
      - hsqldb

  wicket:
    image: wicket:latest
    restart: always
    container_name: wicket_container
    environment:
      APP_NAME: 'wicket'
      HSQLDB_HOST: hsqldb
      HSQLDB_USER: SA
      HSQLDB_PASSWORD:
    build:
      context: com.qulix.yurkevichvv.trainingtask.wicket
    ports:
      - "81:8080"
    depends_on:
      - hsqldb

  hsqldb:
    image: hsqldb
    container_name: hsqldb_container
    volumes:
      - ./com.qulix.yurkevichvv.trainingtask.database/database:/opt/local/hsqldb
      - ./com.qulix.yurkevichvv.trainingtask.database/sql-scripts:/scripts
    build:
      context: com.qulix.yurkevichvv.trainingtask.database
    env_file:
      - ./com.qulix.yurkevichvv.trainingtask.database/hsqldb-compose.env
    ports:
      - "9001:9001"
    tty: true
