version: '3'

services:

  servlet:
    image: servlet:latest
    restart: always
    container_name: servlet_container
    environment:
      APP_NAME: 'servlet'
      HSQLDB_HOST: hsqldb
      HSQLDB_USER: SA
      HSQLDB_PASSWORD:
    build:
      context: com.qulix.yurkevichvv.trainingtask.servlets
    ports:
      - "80:8080"
    depends_on:
      - hsqldb

  wicket:
    image: wicket:latest
    restart: always
    container_name: wicket_container
    environment:
      APP_NAME: 'wicket'
      HSQLDB_HOST: hsqldb
      HSQLDB_USER: SA
      HSQLDB_PASSWORD:
    build:
      context: com.qulix.yurkevichvv.trainingtask.wicket
    ports:
      - "81:8080"
    depends_on:
      - hsqldb

  hsqldb:
    image: hsqldb:latest
    container_name: hsqldb_container
    volumes:
      - ./com.qulix.yurkevichvv.trainingtask.database/database:/usr/local/hsqldb
      - ./com.qulix.yurkevichvv.trainingtask.database/sql-scripts:/usr/local/scripts
    environment:
      APP_NAME: 'hsqldb'
      HSQLDB_DATABASE_NAME: mydb
      HSQLDB_DATABASE_ALIAS: mydb
      HSQLDB_USER: SA
      HSQLDB_PASSWORD:
    build:
      context: com.qulix.yurkevichvv.trainingtask.database
    ports:
      - "9001:9001"