CREATE TABLE IF NOT EXISTS project(
                                      project_id INT GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL PRIMARY KEY,
                                      title VARCHAR(50) NOT NULL,
                                      description VARCHAR(250)
);

CREATE TABLE IF NOT EXISTS employee(
                                       employee_id INT GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL PRIMARY KEY,
                                       surname VARCHAR(50) NOT NULL,
                                       first_name VARCHAR(50) NOT NULL,
                                       patronymic VARCHAR(50) NOT NULL,
                                       post VARCHAR(50) NOT NULL

);

CREATE TABLE IF NOT EXISTS task(
                                    id INT GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL PRIMARY KEY,
                                    status VARCHAR(50) NOT NULL,
                                    title VARCHAR(50) NOT NULL,
                                    work_time BIGINT NOT NULL,
                                    begin_date DATE NOT NULL,
                                    end_date DATE NOT NULL,
                                    employee_id INT,
                                    project_id INT ,
                                    FOREIGN KEY (project_id) REFERENCES project(project_id) ON DELETE SET NULL ON UPDATE CASCADE ,
                                    FOREIGN KEY (employee_id) REFERENCES employee(employee_id) ON DELETE SET NULL ON UPDATE CASCADE
);
