CREATE TABLE IF NOT EXISTS project(
                                      project_id INT GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL PRIMARY KEY,
                                      title VARCHAR(250) NOT NULL,
                                      discription VARCHAR(1000)
);

CREATE TABLE IF NOT EXISTS employee(
                                       employee_id INT GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL PRIMARY KEY,
                                       surname VARCHAR(250) NOT NULL,
                                       first_name VARCHAR(250) NOT NULL,
                                       last_name VARCHAR(250) NOT NULL,
                                       post VARCHAR(250) NOT NULL

);

CREATE TABLE IF NOT EXISTS tasks(
                                    id INT GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL PRIMARY KEY,
                                    flag VARCHAR(250) NOT NULL,
                                    title VARCHAR(250) NOT NULL,
                                    work_time BIGINT NOT NULL,
                                    begin_date DATE NOT NULL,
                                    end_date DATE NOT NULL,
                                    employee_id INT,
                                    project_id INT ,
                                    FOREIGN KEY (project_id) REFERENCES project(project_id) ON DELETE SET NULL ON UPDATE CASCADE ,
                                    FOREIGN KEY (employee_id) REFERENCES employee(employee_id) ON DELETE SET NULL ON UPDATE CASCADE
);
