SET DATABASE SQL SYNTAX MYS TRUE;

CREATE TABLE IF NOT EXISTS project (
    id          INT GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL PRIMARY KEY,
    title       VARCHAR(50)                                                        NOT NULL,
    description VARCHAR(250)                                                       NOT NULL
);

CREATE TABLE IF NOT EXISTS employee (
    id          INT GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL PRIMARY KEY,
    surname     VARCHAR(50)                                                        NOT NULL,
    first_name  VARCHAR(50)                                                        NOT NULL,
    patronymic  VARCHAR(50)                                                        NOT NULL,
    post        VARCHAR(50)                                                        NOT NULL
);

CREATE TABLE IF NOT EXISTS task (
    id          INT GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL PRIMARY KEY,
    status      INT                                                                NOT NULL,
    title       VARCHAR(50)                                                        NOT NULL,
    work_time   BIGINT                                                             NOT NULL,
    begin_date  DATE                                                               NOT NULL,
    end_date    DATE                                                               NOT NULL,
    employee_id INT
        REFERENCES employee ON UPDATE CASCADE ON DELETE SET NULL,
    project_id  INT                                                                NOT NULL
        REFERENCES project ON UPDATE CASCADE ON DELETE CASCADE
);




